FEAT: CAP-19 - Implementing Spring Security with User Class
mfsl-capstone/mfsl-backend pull request #14
Opened 2024-01-31 04:21 UTC by abhijeetpraveen

## Description

**JIRA Ticket:** [CAP-19](https://mfslcapstone.atlassian.net/browse/CAP-19)

**Screenshots/Examples of Changes:**

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-functional change which does not add or remove functionality)

## Checklist

- [x] My branch and PR name follow the [naming conventions](https://mfslcapstone.atlassian.net/wiki/spaces/SD/pages/4358145/Development+Naming+Conventions) the team has established.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules. (If not, this should be a draft PR)
- [x] I have [rebased](https://mfslcapstone.atlassian.net/wiki/spaces/SD/pages/4456479/How+To%3A+Rebase+Branch+Onto+Main) my branch onto main before opening this PR, and resolved any merge conflicts.
- [x] I have ensured that new and existing integrations work with my changes.
- [x] I have set `@EnableMethodSecurity(securedEnabled)` to true in SecurityConfiguration.java

**Dependencies (if applicable):**

---

2024-01-31 04:27 UTC, abhijeetpraveen commented
@seb8stien1 @linamoufarreh Password validation hasn't been implemented in the UserService but based on what I could researched, it is usually handled by the backend. So, it would make sense for us to do it in the UserService class.

2024-01-31 04:30 UTC, abhijeetpraveen commented on src/main/java/capstone/mfslbackend/controller/TeamController.java
> +    @Secured({"LEAGUE_MEMBER", "LEAGUE_ADMIN"})
@linamoufarreh @seb8stien1 This tag allows you to set which user roles can call that controller method.

For example, if we want certain controller methods to be only called by admin, we would just have `"LEAGUE_ADMIN"` in this tag.

2024-01-31 04:32 UTC, abhijeetpraveen commented on src/main/java/capstone/mfslbackend/service/UserService.java
> +        user.getAuthorities().add(Authority.LEAGUE_MEMBER);
@seb8stien1 @linamoufarreh Right now every new user is made with the league member role. Based on how you guys implement the member and admin roles, change this accordingly.

2024-02-02 19:15 UTC, seb8stien1 requested changes

2024-02-02 19:15 UTC, seb8stien1 commented on src/main/java/capstone/mfslbackend/service/LoginService.java
> +    @Transactional
@Transactional on the class means you don't need it because it automatically applies to all public methods

2024-02-02 19:15 UTC, seb8stien1 commented on src/main/java/capstone/mfslbackend/service/LoginService.java
> +    @Transactional
Same

2024-02-04 23:52 UTC, seb8stien1 approved these changes

2024-02-05 01:05 UTC, merged